language: android

jdk:
  - oraclejdk8

env:
    global:
        - NDK_VERSION=r12b
        - NDK_CCACHE=ccache
        - ANDROID_NDK_HOME=$HOME/.android/android-ndk-${NDK_VERSION}
        - SBTPATH=$HOME/.sbt
        - PATH=${ANDROID_NDK_HOME}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${PATH}

scala:
    - 2.11.8

before_cache:
    - find $HOME/.sbt -name "*.lock" | xargs rm
    - find $HOME/.ivy2 -name "*.lock" | xargs rm

cache:
    directories:
        - $HOME/.ivy2
        - $HOME/.sbt

android:
    components:
        - tools
        - build-tools-25.0.2
        - extra-android-m2repository

install:
    - >
      if [ ! -d "$ANDROID_NDK_HOME" ]; then
          mkdir -p $ANDROID_NDK_HOME;
          pushd $HOME/.android;
          export ARCH=`uname -m`;
          wget -q http://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux-${ARCH}.zip;
          unzip -q android-ndk-${NDK_VERSION}-linux-${ARCH}.zip;
          popd;
      fi
    - >
      if [ ! -f "$SBTPATH/sbt" ]; then
          pushd $SBTPATH;
          wget -q https://raw.githubusercontent.com/paulp/sbt-extras/master/sbt;
          chmod a+x sbt;
          popd;
      fi

script:
    - $SBTPATH/sbt android:package

before_deploy:
      - git config --local user.name "xiuluo"
      - git config --local user.email "chen919695074@gmail.com"
      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
      - find $HOME/ -name "obfs-local-debug.apk" -exec mv {} $HOME/ \;
deploy:
  provider: releases
  api_key:
    secure: "jprWzHU3QzgftyKPG09+p2gFK678mL+J8mk6I53XP6ELiN/YJ/iH2OueYIjK3fBFRaDGqNMNe7vCP2gj3OCyT8BdgwDjb2UKENhs3h1CGYPGrCaukN6l2eITGg3Ii/vepdShWC3doyl45zMecKgVS0Gx+JH+HrjoUwrekgH4IDHmkATQz3M1NZ713ebVAEmn0xYGmOr2oJFpULpf8BvM4aec8g6fAVUMdrCQKtdYkgOp7c6YZbrTJIUW4FujBrOuGB0Ou8ZYV+2zid9M3rLEkmCDr/xPL8XVf4UYD+EhP5q//fPCyK5qIdZBaM7sJtHsz2UNy9vdaC0NdOM/JOAcxj5RCi/uZuguHhemzETzdmqZlWBaWbHT5UP+49gwBh7nWHF0mQx1aynFn3E2CtWBEEoA3Zu/69FNWwqUlNTRj4OU51lFndv8fBIjC7opJpFezbahmnz35fgrYLLrqXLFU5/jKAC9izbCqhix16vEcOaKrRJ6nGhxwC6zhmO2ayAcz6NwaEc/7Ivj7r+EQikJhZOwZOG82oi1O4FxbNefOqdhNSLlorge39mVCUAB8z8XRvIHX98x/Z6VDVQmRsmcY5L03V0Pb+1yZaPQmqen1Dv+8Z75tXjqI8StL8D+eTv5w66ozULRwiqo61u7A/uj6jw61hglhcdEpf9dSSZX37I="
  file: "$HOME/obfs-local-debug.apk"
  skip_cleanup: true
